INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('AF', 'DEPARTMENT OF THE AIR FORCE', '1500', 'AF', '57');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('AG', 'DEPARTMENT OF AGRICULTURE', '400', 'AG', '12');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('AM', 'U.S. AGENCY FOR INTERNATIONAL DEVELOPMENT', '4400', 'AM', '72');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('AR', 'DEPARTMENT OF THE ARMY', '1600', 'AR', '21');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('CM', 'DEPARTMENT OF COMMERCE', '500', 'CM', '13');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('CU', 'NATIONAL CREDIT UNION ADMINISTRATION', '3400', 'CU', '25');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('DD', 'DEPARTMENT OF DEFENSE', '600', 'DD', '97');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('DJ', 'DEPARTMENT OF JUSTICE', '1200', 'DJ', '15');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('DL', 'DEPARTMENT OF LABOR', '1300', 'DL', '16');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('DN', 'DEPARTMENT OF ENERGY', '800', 'DN', '89');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('ED', 'DEPARTMENT OF EDUCATION', '700', 'ED', '91');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('EE', 'EQUAL EMPLOYMENT OPPORTUNITY COMMISSION', '2300', 'EE', '45');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('EP', 'ENVIRONMENTAL PROTECTION AGENCY', '2200', 'EP', '68');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('FC', 'FEDERAL COMMUNICATIONS COMMISSION', '2400', 'FC', '27');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('FD', 'FEDERAL DEPOSIT INSURANCE CORPORATION', '2500', 'FD', '51');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('FQ', 'COURT SERVICES AND OFFENDER SUPERVISION AGENCY FOR THE DISTRICT OF COLUMBIA', '300', 'FQ', '95');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('FR', 'FEDERAL RESERVE SYSTEM', '2600', 'FR', '');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('FT', 'FEDERAL TRADE COMMISSION', '2700', 'FT', '29');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('GS', 'GENERAL SERVICES ADMINISTRATION', '2800', 'GS', '47');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('HE', 'DEPARTMENT OF HEALTH AND HUMAN SERVICES', '900', 'HE', '75');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('HS', 'DEPARTMENT OF HOMELAND SECURITY', '1000', 'HS', '70');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('HU', 'DEPARTMENT OF HOUSING AND URBAN DEVELOPMENT', '1100', 'HU', '86');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('IB', 'BROADCASTING BOARD OF GOVERNORS', '200', 'IB', '95');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('IN', 'DEPARTMENT OF THE INTERIOR', '1700', 'IN', '14');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('Judicial', 'JUDICIAL BRANCH', '3000', '', '10');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('Legislative', 'LEGISLATIVE BRANCH', '3100', '', '');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('LP', 'GOVERNMENT PRINTING OFFICE', '2900', 'LP', '');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('NF', 'NATIONAL SCIENCE FOUNDATION', '3600', 'NF', '49');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('NL', 'NATIONAL LABOR RELATIONS BOARD', '3500', 'NL', '63');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('NN', 'NATIONAL AERONAUTICS AND SPACE ADMINISTRATION', '3200', 'NN', '80');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('NQ', 'NATIONAL ARCHIVES AND RECORDS ADMINISTRATION', '3300', 'NQ', '88');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('NU', 'NUCLEAR REGULATORY COMMISSION', '3700', 'NU', '31');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('NV', 'DEPARTMENT OF THE NAVY', '1800', 'NV', '17');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('OM', 'OFFICE OF PERSONNEL MANAGEMENT', '3800', 'OM', '24');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('OtherAgency', 'OTHER AGENCY', '4500', '', '');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('PU', 'PEACE CORPS', '3900', 'PU', '11');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('SB', 'SMALL BUSINESS ADMINISTRATION', '4100', 'SB', '73');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('SE', 'SECURITIES AND EXCHANGE COMMISSION', '4000', 'SE', '50');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('SM', 'SMITHSONIAN INSTITUTION', '4200', 'SM', '33');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('ST', 'DEPARTMENT OF STATE', '1400', 'ST', '19');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('SZ', 'SOCIAL SECURITY ADMINISTRATION', '4300', 'SZ', '28');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('TD', 'DEPARTMENT OF TRANSPORTATION', '2000', 'TD', '69');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('TR', 'DEPARTMENT OF THE TREASURY', '1900', 'TR', '20');
INSERT INTO `URS`.`Agency` (`AgencyID`, `AgencyName`, `DisplayOrder`, `OPMCode`, `TreasuryCode`) VALUES ('VA', 'DEPARTMENT OF VETERANS AFFAIRS', '2100', 'VA', '36');
