CREATE TABLE `AspNetUsers` (
  `Id` varchar(767) NOT NULL,
  `UserName` varchar(256) DEFAULT NULL,
  `NormalizedUserName` varchar(256) DEFAULT NULL,
  `Email` varchar(256) DEFAULT NULL,
  `NormalizedEmail` varchar(256) DEFAULT NULL,
  `EmailConfirmed` tinyint(1) NOT NULL,
  `PasswordHash` text,
  `SecurityStamp` text,
  `ConcurrencyStamp` text,
  `PhoneNumber` text,
  `PhoneNumberConfirmed` tinyint(1) NOT NULL,
  `TwoFactorEnabled` tinyint(1) NOT NULL,
  `LockoutEnd` timestamp NULL DEFAULT NULL,
  `LockoutEnabled` tinyint(1) NOT NULL,
  `AccessFailedCount` int(11) NOT NULL,
  `FirstName` text NOT NULL,
  `MiddleName` text,
  `LastName` text NOT NULL,
  `JobTitle` text NOT NULL,
  `AgencyID` varchar(767) NOT NULL,
  `SubAgencyID` varchar(767) NOT NULL,
  `DateRegistered` datetime NOT NULL,
  `DateAccountExpires` datetime NOT NULL,
  `DatePasswordExpires` datetime NOT NULL,
  `RulesOfBehaviorAgreedTo` tinyint(1) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE KEY `UserNameIndex` (`NormalizedUserName`),
  KEY `IX_AspNetUsers_AgencyID` (`AgencyID`),
  KEY `EmailIndex` (`NormalizedEmail`),
  KEY `IX_AspNetUsers_SubAgencyID` (`SubAgencyID`),
  CONSTRAINT `FK_AspNetUsers_Agency_AgencyID` FOREIGN KEY (`AgencyID`) REFERENCES `Agency` (`AgencyID`) ON DELETE CASCADE,
  CONSTRAINT `FK_AspNetUsers_SubAgency_SubAgencyID` FOREIGN KEY (`SubAgencyID`) REFERENCES `SubAgency` (`SubAgencyID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;